version: '3.8'
services:
  ## Backend API
  overlay-services:
    build:
      context: .
    restart: always
    ports:  
    - "3103:3103"
    - 9229:9229
    environment:
      HOSTING_DOMAIN: 'http://localhost:3103'
      BSV_NETWORK: 'testnet'
      PORT: 3103
      SERVER_PRIVATE_KEY: 'f8b4b466417e3fede5f95cb0651fb6371c3c9c0753a3e15c1c30155461d03c18' # Example Key - Use your own key!
      KNEX_DB_CLIENT: mysql
      KNEX_DB_CONNECTION: '{"port":3113,"host":"overlay-services-mysql","user":"root","password":"test","database":"overlay-services"}'
      NODE_ENV: development
      MIGRATE_KEY: 'my-grate-key'
      DB_CONNECTION: ''
    # depends_on:
      # - overlay-services-mysql
    # networks:
    #   - node-webapp-network
    # links:
    #   - 
      

  ## Backend database
  overlay-services-mysql:
    image: "mysql:8.0"
    platform: linux/x86_64
    hostname: 'overlay-services'
    command: 'mysqld --default-authentication-plugin=mysql_native_password --sync_binlog=0 --innodb_doublewrite=OFF  --innodb-flush-log-at-trx-commit=0 --innodb-flush-method=nosync'
    restart: always
    volumes:
      - './data/overlay-services-data:/var/lib/mysql'
    environment:
      MYSQL_HOST: "127.0.0.1"
      MYSQL_TCP_PORT: 3113
      MYSQL_ROOT_PASSWORD: "test"
      MYSQL_ROOT_HOST: '%'
      MYSQL_DATABASE: "overlay-services"
    ports:
      - "3113:3113"
    healthcheck:
      test: ["CMD-SHELL", 'mysqladmin ping']
      interval: 10s
      timeout: 5s
      retries: 10